# Generated by Django 2.1 on 2020-04-16 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelayGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('r_status', models.BooleanField(default=False)),
                ('r_lastupdateinfo', models.DateTimeField(default=datetime.datetime(2020, 4, 16, 21, 32, 33, 885928))),
            ],
            options={
                'db_table': 'RelayGroup',
            },
        ),
    ]
