# Generated by Django 2.1 on 2020-04-20 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextapp', '0002_auto_20200416_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaygroup',
            name='r_lastupdateinfo',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 10, 41, 43879)),
        ),
    ]
